version: '3.8'
services:
  go-api:
    container_name: interact-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - pics:/app/public/
      - logs:/app/log/

  postgres:
    image: postgres
    container_name: interact-postgres-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    container_name: interact-redis-db
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data

volumes:
  postgres:
    name: postgres-db
    driver: local
  redis:
    name: redis-db
    driver: local
  pics:
    name: storage-db
    driver: local
  logs:
    name: logs-db
    driver: local