version: '3.8'

networks:
  interact-network:
    driver: bridge

services:
  go-api:
    container_name: interact-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:${PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - pics:/app/public/
      - logs:/app/log/
    networks:
      - interact-network

  postgres:
    image: postgres
    container_name: interact-postgres-db
    restart: always
    ports:
      - 5432:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - interact-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis
    container_name: interact-redis-db
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - interact-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    name: postgres-db
    driver: local
  pics:
    name: storage-db
    driver: local
  logs:
    name: logs-db
    driver: local
